name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW-w64
      run: |
        # 安装 MinGW-w64 的步骤，可能需要根据你的具体需求调整
        # 例如，使用 choco 安装 MinGW-w64
        choco install mingw

    - name: Compile project
      run: |
        # 运行 make 命令
        make -f Makefile.mingw_x86_64

    - name: Upload gnb
        uses: actions/upload-artifact@v3
        with:
          name: gnb
          path: ./gnb.exe
    
    - name: Upload gnb
        uses: actions/upload-artifact@v3
        with:
          name: gnb_crypto
          path: ./gnb_crypto.exe

    - name: Upload gnb
        uses: actions/upload-artifact@v3
        with:
          name: gnb_ctl
          path: ./gnb_ctl.exe

    - name: Upload gnb
        uses: actions/upload-artifact@v3
        with:
          name: gnb_es
          path: ./gnb_es.exe
